// Shapes shared by the Log sheet (client) and its server actions.
import type { MediaItem } from "@/lib/storage/paths";
import type { LogAppointment } from "@/lib/appointments/types";

export type LogTarget = {
  accountId?: string | null;
  contactId?: string | null;
  propertyId?: string | null;
  opportunityId?: string | null;
  /** Logging the outcome of this appointment (Today / Go / the appointment page): completes it. */
  appointmentId?: string | null;
};

export type ContactOption = { id: string; name: string; title: string | null; persona_role: string; account_id: string | null; account_name?: string | null };

export type LogContextData = {
  account: { id: string; name: string } | null;
  contact: ContactOption | null;
  contacts: ContactOption[];
  properties: { id: string; label: string }[];
  opportunities: { id: string; name: string }[];
  points: Record<string, number>;
  today: string;
  /** Set when logging an appointment's outcome: channel defaults from its kind; >1 building offers "log each building". */
  appointment?: { id: string; title: string; kind: string; channel: string; buildings: number; status: string } | null;
};

export type LogInput = LogTarget & {
  channel: string;
  outcome: string;
  notes?: string | null;
  metRole?: string | null;
  followUpOn?: string | null;
  followUpNote?: string | null;
  skipFollowUp?: boolean;
  source?: "rep" | "field";
  /** uuid generated by the client per log attempt (see useLogTouch); makes retries/double-taps safe. */
  idempotencyKey?: string | null;
  /** Photos already uploaded to /api/media (touch.media). Roof walks / inspections with photos earn site-walk points. */
  media?: MediaItem[];
  /** When the rep actually tapped (offline replays): becomes touch.occurred_at. Defaults to now. */
  occurredAt?: string | null;
  /** The company the log was made in (offline replays after a company switch). Must be one of the rep's. */
  tenantId?: string | null;
  /** "Log each building": one touch per building of the appointment (else one touch at the account). */
  eachBuilding?: boolean;
  /** Booked inspection → "When?": also schedule the appointment (same action; skipping is fine). */
  appointment?: LogAppointment | null;
};

export type LogResult =
  | {
      ok: true;
      touchId: string;
      points: number;
      awards: { event: string; points: number }[];
      closed: number;
      next: { title: string; due_on: string } | null;
      toast: string;
      /** Set when the log also scheduled an appointment. */
      appointmentId?: string | null;
    }
  /** retryable: no signal / server unreachable — the offline queue keeps it and replays. Otherwise the rep must fix it. */
  | { ok: false; error: string; retryable?: boolean };

export type SimilarContact = { id: string; full_name: string | null; email: string | null; phone: string | null; account_name: string | null; similarity: number | null };

export type QuickContactInput = {
  accountId?: string | null;
  propertyId?: string | null;
  fullName: string;
  title?: string | null;
  personaRole?: string | null;
  phone?: string | null;
  email?: string | null;
  source?: "rep" | "field";
  /** Skip the duplicate check (the rep said "No, this is someone new"). */
  force?: boolean;
  /** From a business-card scan. */
  mobile?: string | null;
  notes?: string | null;
  /** Storage key of the scanned card (contact.source_image_path). */
  sourceImagePath?: string | null;
};

export type QuickContactResult =
  | { ok: true; contact: ContactOption }
  | { ok: false; duplicates: SimilarContact[]; error?: undefined }
  | { ok: false; error: string; duplicates?: undefined };

export type SearchHit = { kind: "contact" | "account"; id: string; name: string; sub: string | null; accountId: string | null };
