/**
 * Generates src/lib/db/database.types.ts from a live Postgres (local test DB or Supabase) in the shape
 * supabase-js expects. Equivalent to `supabase gen types typescript`, without needing the CLI/Docker.
 *
 *   DATABASE_URL=postgresql://... npx tsx scripts/gen-types.ts
 */
import { Client } from "pg";
import { writeFileSync } from "node:fs";

const url = process.env.DATABASE_URL ?? "postgresql://postgres@localhost:54329/dilly_test?host=/tmp";

const PG_TO_TS: Record<string, string> = {
  uuid: "string", text: "string", citext: "string", varchar: "string", bpchar: "string",
  int2: "number", int4: "number", int8: "number", float4: "number", float8: "number", numeric: "number",
  bool: "boolean", date: "string", timestamptz: "string", timestamp: "string", time: "string",
  json: "Json", jsonb: "Json",
};

function tsType(udt: string, isArray: boolean) {
  const base = PG_TO_TS[udt.replace(/^_/, "")] ?? "string"; // app.* domains are text
  return isArray ? `${base}[]` : base;
}

async function main() {
  const c = new Client({ connectionString: url });
  await c.connect();
  const cols = await c.query(`
    select c.table_name, c.column_name, c.is_nullable = 'YES' as nullable, c.column_default is not null as has_default,
           c.is_generated = 'ALWAYS' or c.is_identity = 'YES' as generated,
           coalesce(bt.typname, t.typname) as udt, t.typcategory = 'A' as is_array, tb.table_type
      from information_schema.columns c
      join information_schema.tables tb on tb.table_schema = c.table_schema and tb.table_name = c.table_name
      join pg_type t on t.typname = c.udt_name
      left join pg_type bt on t.typtype = 'd' and bt.oid = t.typbasetype
     where c.table_schema = 'public'
     order by c.table_name, c.ordinal_position`);
  const fns = await c.query(`
    select p.proname, pg_get_function_arguments(p.oid) as args, pg_get_function_result(p.oid) as result
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind = 'f'
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
     order by p.proname`);
  await c.end();

  const tables = new Map<string, typeof cols.rows>();
  const views = new Map<string, typeof cols.rows>();
  for (const r of cols.rows) {
    const m = r.table_type === "VIEW" ? views : tables;
    if (!m.has(r.table_name)) m.set(r.table_name, []);
    m.get(r.table_name)!.push(r);
  }

  const out: string[] = [];
  out.push("// Generated by scripts/gen-types.ts — do not edit by hand.");
  out.push("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n");
  out.push("export type Database = {\n  public: {\n    Tables: {");
  for (const [name, rs] of tables) {
    const row = rs.map((r) => `          ${r.column_name}: ${tsType(r.udt, r.is_array)}${r.nullable ? " | null" : ""};`).join("\n");
    const ins = rs
      .filter((r) => !r.generated)
      .map((r) => `          ${r.column_name}${r.nullable || r.has_default ? "?" : ""}: ${tsType(r.udt, r.is_array)}${r.nullable ? " | null" : ""};`)
      .join("\n");
    const upd = rs
      .filter((r) => !r.generated)
      .map((r) => `          ${r.column_name}?: ${tsType(r.udt, r.is_array)}${r.nullable ? " | null" : ""};`)
      .join("\n");
    out.push(`      ${name}: {\n        Row: {\n${row}\n        };\n        Insert: {\n${ins}\n        };\n        Update: {\n${upd}\n        };\n        Relationships: [];\n      };`);
  }
  out.push("    };\n    Views: {");
  for (const [name, rs] of views) {
    const row = rs.map((r) => `          ${r.column_name}: ${tsType(r.udt, r.is_array)} | null;`).join("\n");
    out.push(`      ${name}: {\n        Row: {\n${row}\n        };\n        Relationships: [];\n      };`);
  }
  out.push("    };\n    Functions: {");
  for (const f of fns.rows) {
    const args = (f.args as string)
      .split(",")
      .map((a) => a.trim())
      .filter(Boolean)
      .map((a) => {
        const [n, ...rest] = a.replace(/ DEFAULT .*/i, "").split(" ");
        const opt = / DEFAULT /i.test(a) ? "?" : "";
        const raw = rest.join(" ").replace(/^(public|app)\./, "");
        const isArr = raw.endsWith("[]");
        const ty = raw.replace(/\[\]$/, "");
        const base = ty === "boolean" ? "boolean" : /^(integer|smallint|bigint|numeric)$/.test(ty) ? "number" : "string";
        return `${n}${opt}: ${base}${isArr ? "[]" : ""}`;
      })
      .join("; ");
    const isSet = /^TABLE\(/i.test(f.result) || /^SETOF/i.test(f.result);
    let ret = "unknown";
    if (/^TABLE\(/i.test(f.result)) {
      const fields = (f.result as string)
        .slice(6, -1)
        .split(",")
        .map((x) => x.trim().split(" "))
        .map(([n, ...t]) => {
          const ty = t.join(" ");
          const ts = /int|numeric|bigint|smallint|real|double/.test(ty) ? "number" : ty === "boolean" ? "boolean" : "string";
          return `${n}: ${ts} | null`;
        })
        .join("; ");
      ret = `{ ${fields} }[]`;
    } else if (/integer|bigint/.test(f.result)) ret = "number";
    else if (f.result === "boolean") ret = "boolean";
    else if (f.result === "void") ret = "undefined";
    out.push(`      ${f.proname}: { Args: { ${args} }; Returns: ${ret} };`);
    void isSet;
  }
  out.push("    };\n    Enums: Record<string, never>;\n    CompositeTypes: Record<string, never>;\n  };\n};\n");
  out.push(`export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];`);
  out.push(`export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];`);
  out.push(`export type TablesUpdate<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"];`);
  out.push(`export type Views<T extends keyof Database["public"]["Views"]> = Database["public"]["Views"][T]["Row"];\n`);
  writeFileSync("src/lib/db/database.types.ts", out.join("\n"));
  console.log(`wrote ${tables.size} tables, ${views.size} views, ${fns.rows.length} functions`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
